#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri Apr 28 11:40:43 2017

@author: Jessica
"""

import numpy as np
import peakutils


spectrum=np.genfromtxt('../Data/PointSpectra/Spectrum1.txt', delimiter='',
                     skip_header=1)

def FindPeak(spectrum, thres, min_dist):
    peakindices = peakutils.indexes(spectrum[:,1], thres=thres,
                                    min_dist=min_dist)


    